# Generated by Django 5.2.3 on 2025-07-16 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('users', '0002_populate_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='all_properties',
            field=models.BooleanField(default=False, help_text='Employee has access to all company properties'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='apartment_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='properties.apartmentunit'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='lease_length_months',
            field=models.IntegerField(blank=True, choices=[(3, '3 months'), (6, '6 months'), (12, '12 months')], null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='rent_payment_date',
            field=models.IntegerField(blank=True, help_text='Day of month (1-28)', null=True),
        ),
    ]
