# Generated by Django 5.2.3 on 2025-07-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='payment_start_date',
            field=models.DateField(blank=True, help_text='Date when payment schedule should start', null=True),
        ),
    ]
