# Generated by Django 5.2.3 on 2025-07-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_invitation_payment_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='payment_start_date',
            new_name='lease_start_date',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='lease_start_date',
            field=models.DateField(blank=True, help_text="Date when the tenant's lease begins", null=True),
        ),
    ]
