# Generated by Django 5.2.3 on 2025-07-18 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_add_rent_amount_to_apartment_unit'),
        ('users', '0006_rename_payment_start_date_to_lease_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apartment_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant', to='properties.apartmentunit'),
        ),
    ]
