# Generated by Django 5.2.3 on 2025-07-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_add_rent_amount_to_apartment_unit'),
        ('users', '0007_user_apartment_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='assigned_properties',
            field=models.ManyToManyField(blank=True, help_text='Properties this employee will have access to', related_name='employee_invitations', to='properties.property'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_properties',
            field=models.ManyToManyField(blank=True, help_text='Properties this employee has access to (for employees only)', related_name='assigned_employees', to='properties.property'),
        ),
    ]
