# Generated by Django 5.2.3 on 2025-07-16 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentunit',
            name='rent_amount',
        ),
    ]
