# Generated by Django 5.2.3 on 2025-07-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_apartmentunit_rent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentunit',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
