# Generated by Django 5.2.3 on 2025-07-12 22:25

from django.db import migrations

def create_default_categories(apps, schema_editor):
    DocumentCategory = apps.get_model('documents', 'DocumentCategory')
    
    categories = [
        ('Leases & Contracts', 'Lease agreements, rental contracts, and related legal documents'),
        ('Financial Documents', 'Invoices, receipts, payment records, and financial statements'),
        ('Property Information', 'Property specifications, floor plans, and building information'),
        ('Maintenance Records', 'Maintenance schedules, repair records, and service documentation'),
        ('Insurance & Legal', 'Insurance policies, legal documents, and compliance records'),
        ('Tenant Information', 'Tenant applications, background checks, and personal documents'),
        ('Utilities & Services', 'Utility bills, service contracts, and provider information'),
        ('Communications', 'Notices, announcements, and correspondence'),
        ('Policies & Procedures', 'Company policies, procedures, and guidelines'),
        ('Miscellaneous', 'Other documents that don\'t fit into specific categories'),
    ]
    
    for name, description in categories:
        DocumentCategory.objects.get_or_create(
            name=name,
            defaults={'description': description}
        )

def remove_default_categories(apps, schema_editor):
    DocumentCategory = apps.get_model('documents', 'DocumentCategory')
    category_names = [
        'Leases & Contracts',
        'Financial Documents', 
        'Property Information',
        'Maintenance Records',
        'Insurance & Legal',
        'Tenant Information',
        'Utilities & Services',
        'Communications',
        'Policies & Procedures',
        'Miscellaneous',
    ]
    DocumentCategory.objects.filter(name__in=category_names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]
