# Generated by Django 5.2.3 on 2025-07-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20250712_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='actual_cost',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='maintenanceupdate',
            name='cost_estimate',
        ),
        migrations.AlterField(
            model_name='maintenanceupdate',
            name='update_type',
            field=models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('PROGRESS_UPDATE', 'Progress Update'), ('SCHEDULING', 'Scheduling'), ('COMPLETION', 'Completion'), ('NOTE', 'Note')], default='NOTE', max_length=20),
        ),
    ]
