# Generated by Django 5.2.3 on 2025-07-13 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_populate_document_categories'),
        ('maintenance', '0003_remove_maintenancerequest_actual_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceinvoice',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_invoices', to='documents.document'),
        ),
    ]
